subplot(1,1,1)
ss=0:11;
hold on;
          p1=plot(ss,h(:,2),'-.k','LineWidth',1,...
                'MarkerEdgeColor','g',...
                'MarkerFaceColor','w',...
                'MarkerSize',10);
         p2=plot(ss,h(:,3),'-g','LineWidth',1,...
                'MarkerEdgeColor','k',...
                'MarkerFaceColor','b',...
                'MarkerSize',10);
            p3=plot(ss,h(:,4),'-r','LineWidth',1,...
                'MarkerEdgeColor','k',...
                'MarkerFaceColor','y',...
                'MarkerSize',10);
        xlabel('Iteration #');       
ylabel('Objective Value');
 set(gca,'XTick',[0:11]);
            set(gca,'XTickLabel',{'1';'5';'10';'20';'30';'40';'50';'60';'70';'80';'90';'100'})
% set(gca,'XTickLabel',{'1','5','10','15','20','25'})
% legend([p1,p2,p3,p4,p5,p6],'LNP','LMPROJ','DTSVM','KMM','CD-SVM','MKSLP','Location','SouthEast');
legend([p1,p2,p3],'Inter-subject(DEAP)','DEAP→SI','\{SI, SII, SIII\}→DEAP','Location','Best');

% legend([p1,p2,p3,p4,p5,p6,p7,p8,p9],'LLGC','S-RLSC','LNP','DASVM','LMPROJ','DTSVM','KMM','SLPDAL','MKSLP','Location','SouthEast');
grid on;
box on;
hold off; 