% s = [1:10];
% s=s';
% ss1=[1e2:1e2:(1e3-1e2),1e3:1e3:(1e4-1e3),1e4:1e4:(1e5-1e4),1e5:1e5:(1e6-1e5),1e6]';
% ss=[2:0.1:3,3.1:0.1:4,4.1:0.1:5,5.1:0.1:6]';
% ss=[1:10]';
% erdata=data(2:2:24,:);
% accdata=data(1:2:23,:);
% y=f3; %10 classes
%y=f4; % 100 classes
%  y=f5; % 256 classes
%  y=f2;   % 20 classes
y=DiffSourceDEAP;
hold on;
% set(gca,'xscale','log');
          p1=plot(y(:,1),y(:,2),'-.k^','LineWidth',2,...
                'MarkerEdgeColor','g',...
                'MarkerFaceColor','w',...
                'MarkerSize',10);
         p2=plot(y(:,1),y(:,3),'-gs','LineWidth',2,...
                'MarkerEdgeColor','k',...
                'MarkerFaceColor','b',...
                'MarkerSize',10);
            p3=plot(y(:,1),y(:,4),'-rd','LineWidth',2,...
                'MarkerEdgeColor','k',...
                'MarkerFaceColor','y',...
                'MarkerSize',10);
            p4=plot(y(:,1),y(:,5),'-cx','LineWidth',2,...
                'MarkerEdgeColor','k',...
                'MarkerFaceColor','b',...
                'MarkerSize',10);
%              p5=plot(y(:,1),y(:,6),'-m>','LineWidth',2,...
%                 'MarkerEdgeColor','k',...
%                 'MarkerFaceColor','b',...
%                 'MarkerSize',10);
             p6=plot(y(:,1),y(:,7),'-bo','LineWidth',2,...
                'MarkerEdgeColor','k',...
                'MarkerFaceColor','r',...
                'MarkerSize',10);
%              p7=plot(y(:,1),y(:,8),'-k^','LineWidth',2,...
%                 'MarkerEdgeColor','k',...
%                 'MarkerFaceColor','c',...
%                 'MarkerSize',10);
%             p8=plot(y(:,1),y(:,9),'-gs','LineWidth',2,...
%                 'MarkerEdgeColor','k',...
%                 'MarkerFaceColor','k',...
%                 'MarkerSize',10);
%             p9=errorbar(ss,accdata(:,9),erdata(:,9),'-k<','LineWidth',2,...
%                 'MarkerEdgeColor','k',...
%                 'MarkerFaceColor','g',...
%                 'MarkerSize',10);
%             set(gca,'XTickLabel',{'0','Split1','Split2','Split3','Split4','Split5','Split6'})
% %set(gca,'YTickLabel',{'0.6','0.7','0.8','0.9','1'})
%   xlabel('\omega');       
% ylabel('Accuracy');
axis([0,2400,33,65])
% set(gca,'xtick',0:500:2300) 
xlabel('Number of source data');       
ylabel('Emotion Recognition Rate(%)');
% legend([p1,p2,p3,p4,p5,p6],'LNP','LMPROJ','DTSVM','KMM','CD-SVM','MKSLP','Location','SouthEast');
% legend([p2,p4,p5,p6,p7],'SLRR','FastDAM','Multi-KT','A-SVM','RMAVC','Location','SouthEast');
legend([p1,p2,p3,p4,p6],'FastDAM','MACI','Multi-KT','DSM','A-SVM','Location','SouthEast');
grid on;
box on;
hold off