% ss=[2:0.1:3,3.1:0.1:4,4.1:0.1:5,5.1:0.1:6]';
hold on;
% set(gca,'xscale','log');
% set(gca,'yscale','log');
% ss1=log(ss);
% data1=log(data);
% data2=data1(1:10,1:3);
% p1=plot(lambda(:,1),deap(:,1),'-k^','LineWidth',2,...
%                 'MarkerEdgeColor','k',...
%                 'MarkerFaceColor','g',...
%                 'MarkerSize',10);
%             
%  p2=plot(lambda(:,1),deap(:,2),'-.b*','LineWidth',2,...
%                 'MarkerEdgeColor','k',...
%                 'MarkerFaceColor','b',...
%                 'MarkerSize',10);
%             p3=plot(lambda(:,1),seed(:,1),'-md','LineWidth',2,...
%                 'MarkerEdgeColor','k',...
%                 'MarkerFaceColor','y',...
%                 'MarkerSize',10);
%             
%            p4=plot(lambda(:,1),seed(:,2),'-rx','LineWidth',2,...
%                 'MarkerEdgeColor','k',...
%                 'MarkerFaceColor','b',...
%                 'MarkerSize',10);
             p5=plot(lambda(:,1),seed4(:,1),'-g>','LineWidth',2,...
                'MarkerEdgeColor','k',...
                'MarkerFaceColor','b',...
                'MarkerSize',10);
             p6=plot(lambda(:,1),seed4(:,2),'-co','LineWidth',2,...
                'MarkerEdgeColor','k',...
                'MarkerFaceColor','r',...
                'MarkerSize',10);
%      
 set(gca,'XTick',[1:1:8]);
            set(gca,'XTickLabel',{'0','0.001','0.01','0.1','1','10','100','1000'})
  xlabel('\lambda_s');       
ylabel('Recognition Accuracy (%)');
legend([p5,p6],'Prediction Consistency','Ground-truth Consistency','Location','Best');
% legend([p1,p2,p3,p4,p5,p6,p7,p8,p9],'LLGC','S-RLSC','LNP','DASVM','LMPROJ','DTSVM','KMM','SLPDAL','MKSLP','Location','SouthEast');
grid on;
box on;
hold off; 

    